services:
    app:
        build: .
        ports:
            - "8000:8000"
        command: sh runserver.sh
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./:/app
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - .env

volumes:
    db_data: